name: gcp_de_data_pipeline_dbt
version: '1.0'
config-version: 2

profile: gcp_dbt_profile

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
    curation:
      +materialized: table